### ISSUE TITLE
Error 500

### ISSUE THREAD

**Issue by Dechorgnat** [pauldechorgnat/wine_app#2]
OperationalError: (sqlite3.OperationalError) no such table: user [SQL: u'SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen \nFROM user \nWHERE user.id = ?'] [parameters: (2,)]

**Comment by Dechorgnat** [comment]
app.db vanishes in last commits ;)

**Comment by pauldechorgnat** [comment]
Yep my bad
